### ISSUE TITLE
Timeout while getting 'https://youtube.com/login'

### ISSUE THREAD

**Issue by infopcgood** [7x11x13/youtube-up#4]
Relevant error log:
```
    uploader.upload(filename, metadata)
  File "(REDACTED)/venv/lib/python3.11/site-packages/youtube_up/uploader.py", line 149, in upload
    self._get_session_token()
  File "(REDACTED)/venv/lib/python3.11/site-packages/youtube_up/uploader.py", line 253, in _get_session_token
    driver.get("https://youtube.com/upload")
  File "(REDACTED)/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "(REDACTED)/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "(REDACTED)/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Navigation timed out after 300000 ms
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5
TimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:723:5
bail@chrome://remote/content/marionette/sync.sys.mjs:211:19
```

**Comment by infopcgood** [comment]
Update: When I manually give the SESSION_TOKEN in the cookies.txt file, everything else functions normally.

**Comment by 7x11x13** [comment]
Are you able to visit youtube.com/upload in your normal browser? Does restarting your computer/internet do anything?

**Comment by infopcgood** [comment]
> Are you able to visit youtube.com/upload in your normal browser? Does restarting your computer/internet do anything?

I can browse/upload normally.

**Comment by infopcgood** [comment]
How about we just send a POST request to `https://studio.youtube.com/youtubei/v1/ars/grst?alt=json&key=(unidentified key here)`? it seems to return `sessionToken` in the response, and using it as the SESSION_TOKEN works.

**Comment by infopcgood** [comment]
> How about we just send a POST request to `https://studio.youtube.com/youtubei/v1/ars/grst?alt=json&key=(unidentified key here)`? it seems to return `sessionToken` in the response, and using it as the SESSION_TOKEN works.

It seems like the unidentified key is constant. SHA512 of the key is [`0e811b629657d93801177a0eab45524d4e90e55694c30cbd796458647c3dd18fa31ac29a8deb7b978af340681fc6913be883d0f0f77c2c16cfc2a01d92bbabe9`.](https://emn178.github.io/online-tools/sha512.html) Please check if it is same for you.

**Comment by infopcgood** [comment]
> How about we just send a POST request to `https://studio.youtube.com/youtubei/v1/ars/grst?alt=json&key=(unidentified key here)`? it seems to return `sessionToken` in the response, and using it as the SESSION_TOKEN works.

Nevermind, we're already using this.

**Comment by infopcgood** [comment]
Tried on a Windows machine and it's working. I'm assuming it was a problem with my cookies. I'll close this issue when I identify the error.

**Comment by infopcgood** [comment]
Issue closed as I wasn't able to reproduce the issue.

**Comment by 7x11x13** [comment]
> How about we just send a POST request to `https://studio.youtube.com/youtubei/v1/ars/grst?alt=json&key=(unidentified key here)`? it seems to return `sessionToken` in the response, and using it as the SESSION_TOKEN works.

IIRC the request requires some sort of captcha/attestation in the payload as well which is why I used selenium in the first place (so it can just intercept the request as it's made)
